name: MiPrimerWorkflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Plataforma
        run: |
          if [ "$PLATAFORMA" == "AWS" ]; then
            echo "Se está ejecutando en AWS"
          else
            echo "No es AWS"
          fi
    env:
      PLATAFORMA: "AWS"
