name: MiPrimerWorkflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Mostrar Variables de GitHub
       run: |
          echo "Repositorio: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Evento: ${{ github.event_name }}"
        
        
