name: MiPrimerWorkflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Saludo
        run: echo "¡Hola, GitHub Actions!"
        
        env:
  MI_VARIABLE: "¡Hola desde GitHub Actions!"

steps:
  - name: Mostrar Variable
    run: echo "El valor de la variable es $MI_VARIABLE"
